language: node_js
os: linux
dist: focal

cache:
  directories:
    - node_modules

install:
  - npm i pnpm -g
  - pnpm install

jobs:
  include:
    - stage: test code
      addons:
        sonarcloud:
          organization: saitho
      script:
        - pnpm test
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi' # sonar only on non-PRs
    - stage: release
      if: branch = master
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - pnpx semantic-release
